# Generated by Django 2.1.4 on 2019-01-02 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Area Name')),
                ('pincode', models.CharField(max_length=6, verbose_name='PIN Code')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='BuildingComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Building / Society Complex')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Building Complex',
                'verbose_name_plural': 'Building Complexes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='buildingcomplex',
            unique_together={('name', 'area')},
        ),
    ]
