# Generated by Django 2.1.4 on 2018-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='gst_code',
            field=models.CharField(default=1, max_length=2, unique=True, verbose_name='GST Code'),
            preserve_default=False,
        ),
    ]
