# Generated by Django 2.0.6 on 2018-07-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpvalidation',
            name='type',
            field=models.CharField(choices=[('email', 'EMail Address'), ('mobile', 'Mobile Number')], default='email', max_length=15, verbose_name='EMail/Mobile'),
        ),
    ]
