# Generated by Django 2.1.4 on 2019-01-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Raw Material')),
                ('unit_quantity', models.DecimalField(blank=True, decimal_places=3, help_text="If raw material is packaged, what's per unit quantity? Eg: Per Bottle: 1 Litre", max_digits=10, null=True, verbose_name='Per Unit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Raw Material',
                'verbose_name_plural': 'Raw Materials',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.RawMaterialMaster', verbose_name='Raw Material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Raw Material Stock in Warehouse',
                'verbose_name_plural': 'Raw Materials Stock in Warehouse',
            },
        ),
        migrations.CreateModel(
            name='StockCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('date', models.DateField(verbose_name='Date of Input')),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Manufacturing Date')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('mfg_batch', models.CharField(blank=True, max_length=254, null=True, verbose_name='Manufacturing Batch Number')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other details')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.RawMaterialStock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Raw Material Input',
                'verbose_name_plural': 'Raw Material Inputs',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasurementMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Unit of Measurement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit of Measurement',
                'verbose_name_plural': 'Unit of Measurements',
            },
        ),
        migrations.AddField(
            model_name='rawmaterialmaster',
            name='unit_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rawmaterialunitmaster', to='stock.UnitOfMeasurementMaster', verbose_name="Unit's UOM"),
        ),
        migrations.AddField(
            model_name='rawmaterialmaster',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.UnitOfMeasurementMaster', verbose_name='Unit of Measurement'),
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialstock',
            unique_together={('warehouse', 'raw_material')},
        ),
    ]
