# Generated by Django 2.0.7 on 2018-08-10 18:27

from django.db import migrations, models
import django.db.models.deletion
import drfaddons.datatypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHeader',
            fields=[
                ('id', models.CharField(auto_created=True, max_length=254, primary_key=True, serialize=False, verbose_name='Bill Number')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('bill_date', models.DateTimeField(verbose_name='Bill Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('payment_mode', models.CharField(choices=[('C', 'Cash'), ('I', 'Instamojo')], default='I', max_length=3, verbose_name='Mode of Payment')),
                ('paid', models.BooleanField(default=False, verbose_name='Bill Paid')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Full Name')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID')),
                ('order_mode', models.CharField(choices=[('R', 'Dine In'), ('P', 'Pick Up'), ('D', 'Delivery')], default='R', max_length=3, verbose_name='Order Mode')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Billing Header',
                'verbose_name_plural': 'Billing Headers',
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('billheader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.BillingHeader')),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
            },
        ),
    ]
