# Generated by Django 2.0.7 on 2018-07-27 16:16

import billing.models
from django.db import migrations, models
import django.db.models.deletion
import drfaddons.datatypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('bill_date', models.DateTimeField(verbose_name='Bill Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('name', models.CharField(max_length=500, null=True, verbose_name='Full Name')),
                ('mobile', models.CharField(max_length=15, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email ID')),
                ('order_no', models.CharField(default=billing.models.BillingHeader.number, max_length=20, verbose_name='Order Number')),
                ('bill_no', models.CharField(max_length=20, verbose_name='Bill Number')),
            ],
            options={
                'verbose_name': 'Billing Header',
                'verbose_name_plural': 'Billing Headers',
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('billheader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.BillingHeader')),
            ],
            options={
                'verbose_name': 'Bill Item',
                'verbose_name_plural': 'Bill Items',
            },
        ),
    ]
