# Generated by Django 2.0.7 on 2018-07-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingheader',
            name='bill_date',
            field=models.DateTimeField(verbose_name='Bill Date'),
        ),
    ]
