# Generated by Django 2.0.7 on 2018-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180810_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingheader',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
