# Generated by Django 2.0.7 on 2018-08-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180811_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingheader',
            name='bill_date',
            field=models.DateTimeField(auto_created=True, verbose_name='Bill Date'),
        ),
    ]
