# Generated by Django 2.0.7 on 2018-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180727_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingheader',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='billingheader',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='billingheader',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Full Name'),
        ),
    ]
