# Generated by Django 2.0.7 on 2018-08-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180730_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstamojoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('purpose', models.CharField(max_length=254, verbose_name='Purpose')),
                ('redirect_url', models.URLField(verbose_name='Redirect URL')),
                ('allow_repeated_payments', models.BooleanField(default=False, verbose_name='Allow Repeated Payment')),
                ('payment_id', models.CharField(blank=True, max_length=254, null=True, verbose_name='Payment ID')),
                ('payment_raw', models.TextField(blank=True, null=True, verbose_name='Payment Raw Response')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('payment_request_id', models.TextField(blank=True, null=True, verbose_name='Payment Request ID')),
                ('payment_request_raw', models.TextField(blank=True, null=True, verbose_name='Payment Request Raw Response')),
                ('expires_at', models.CharField(blank=True, max_length=30, null=True, verbose_name='Expires at')),
            ],
        ),
        migrations.AddField(
            model_name='billingheader',
            name='payment_done',
            field=models.BooleanField(default=False, verbose_name='Payment Done?'),
        ),
        migrations.AddField(
            model_name='billingheader',
            name='payment_id',
            field=models.TextField(blank=True, null=True, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='billingheader',
            name='payment_mode',
            field=models.CharField(choices=[('C', 'Cash'), ('I', 'Instamojo')], default='I', max_length=3, verbose_name='Mode of Payment'),
        ),
        migrations.AddField(
            model_name='instamojodetails',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.BillingHeader'),
        ),
    ]
