# Generated by Django 2.0.7 on 2018-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180811_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingheader',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email ID'),
        ),
        migrations.AlterField(
            model_name='billingheader',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='billingheader',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Full Name'),
        ),
    ]
