# Generated by Django 2.1.4 on 2018-12-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180813_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingheader',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time'),
        ),
        migrations.AlterField(
            model_name='billingheader',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
    ]
