# Generated by Django 2.0.7 on 2018-08-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180804_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instamojodetails',
            options={'verbose_name': 'Instamojo Detail', 'verbose_name_plural': 'Instamojo Details'},
        ),
    ]
