# Generated by Django 2.1.4 on 2019-01-01 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import outlet.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('unit', models.CharField(blank=True, max_length=254, null=True, verbose_name='Unit No')),
                ('building', models.CharField(max_length=254, verbose_name='Building/Complex Name')),
                ('area', models.CharField(max_length=254, verbose_name='Sector / Area')),
                ('pincode', models.CharField(max_length=6, verbose_name='Pincode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Outlet Phone')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.Business', verbose_name='Business Owner')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.City', verbose_name='City')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outlet',
                'verbose_name_plural': 'Outlets',
            },
        ),
        migrations.CreateModel(
            name='OutletCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ComboProduct', verbose_name='Combo Product')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.Outlet', verbose_name='Outlet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutletImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('name', models.CharField(max_length=154, verbose_name='Image name')),
                ('image', models.ImageField(upload_to=outlet.utils.outlet_image_upload)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.Outlet', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'Outlet Image',
                'verbose_name_plural': 'Outlet Images',
            },
        ),
        migrations.CreateModel(
            name='OutletManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managesoutlet', to=settings.AUTH_USER_MODEL, verbose_name='Manager')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.Outlet', verbose_name='Outlet')),
            ],
            options={
                'verbose_name': 'Outlet Manager',
                'verbose_name_plural': 'Outlet Managers',
            },
        ),
        migrations.CreateModel(
            name='OutletProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.Outlet', verbose_name='Outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Outlet Product',
                'verbose_name_plural': 'Outlet Products',
            },
        ),
        migrations.AlterUniqueTogether(
            name='outletmanager',
            unique_together={('manager', 'outlet')},
        ),
    ]
