# Generated by Django 2.1.4 on 2018-12-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Outlet Phone'),
        ),
    ]
