# Generated by Django 2.1.4 on 2018-12-27 05:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlet', '0002_outlet_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outletmanager',
            unique_together={('manager', 'outlet')},
        ),
    ]
