# Generated by Django 2.1.4 on 2019-01-01 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_auto_20190102_0031'),
        ('outlet', '0002_auto_20190101_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletProcurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('date', models.DateField(verbose_name='Date of Input')),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Manufacturing Date')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('mfg_batch', models.CharField(blank=True, max_length=254, null=True, verbose_name='Manufacturing Batch Number')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other details')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outlet Procurement',
                'verbose_name_plural': 'Outlet Procurements',
            },
        ),
        migrations.CreateModel(
            name='OutletStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.Outlet', verbose_name='Outlet')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.RawMaterialMaster', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name': 'Outlet Stock',
                'verbose_name_plural': 'Outlet Stocks',
            },
        ),
        migrations.CreateModel(
            name='RawMaterialRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('fulfilled_on', models.DateField(blank=True, help_text='When was this request fulfilled?', null=True, verbose_name='Fulfilled On?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.Outlet', verbose_name='Outlet')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.RawMaterialMaster', verbose_name='Raw Material')),
            ],
            options={
                'verbose_name': 'Raw Material Request',
                'verbose_name_plural': 'Raw Material Requests',
            },
        ),
        migrations.AddField(
            model_name='outletprocurement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.OutletStock', verbose_name='Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='outletstock',
            unique_together={('outlet', 'raw_material')},
        ),
    ]
