# Generated by Django 2.1.4 on 2019-01-02 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0004_outlet_serviceable_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='serviceable_area',
            field=models.ManyToManyField(blank=True, related_name='serviced_by_outlet', to='location.Area', verbose_name='Serviceable Areas'),
        ),
    ]
