# Generated by Django 2.1.4 on 2019-01-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0005_auto_20190102_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletcombo',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='outletcombo',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='outletcombo',
            name='outlet',
        ),
        migrations.DeleteModel(
            name='OutletCombo',
        ),
    ]
