# Generated by Django 2.1.4 on 2019-01-02 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outlet', '0006_auto_20190102_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletStockRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('batch_id', models.PositiveIntegerField(verbose_name='Batch Request ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('fulfilled_on', models.DateField(blank=True, help_text='When was this request fulfilled?', null=True, verbose_name='Fulfilled On?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outlet.OutletStock', verbose_name='Outlet Stock')),
            ],
            options={
                'verbose_name': 'Outlet Stock Request',
                'verbose_name_plural': 'Outlet Stock Requests',
            },
        ),
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='rawmaterialrequest',
            name='raw_material',
        ),
        migrations.DeleteModel(
            name='RawMaterialRequest',
        ),
    ]
