# Generated by Django 2.1.4 on 2018-12-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181219_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='d_uom',
            field=models.CharField(blank=True, choices=[('G', 'Grams'), ('KG', 'Kilo Grams'), ('PLT', 'Plates'), ('L', 'Litres'), ('ML', 'Milli Litres'), ('M', 'Meters'), ('KM', 'Kilo Meters'), ('MM', 'Milli Meters'), ('GLS', 'Glasses'), ('CP', 'Cups')], max_length=5, null=True, verbose_name='Default Unit of Measurement'),
        ),
    ]
