# Generated by Django 2.1.4 on 2019-01-01 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_auto_20190102_0031'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('date', models.DateField(verbose_name='Date of Input')),
                ('mfg_date', models.DateField(blank=True, null=True, verbose_name='Manufacturing Date')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Expiry Date')),
                ('mfg_batch', models.CharField(blank=True, max_length=254, null=True, verbose_name='Manufacturing Batch Number')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Other details')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Input',
                'verbose_name_plural': 'Warehouse Inputs',
            },
        ),
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.RawMaterialMaster', verbose_name='Raw Material')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.Warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Warehouse Stock',
                'verbose_name_plural': 'Warehouse Stocks',
            },
        ),
        migrations.AddField(
            model_name='warehouseinput',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.WarehouseStock', verbose_name='Stock'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('warehouse', 'raw_material')},
        ),
    ]
