# Generated by Django 2.1.4 on 2019-01-02 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('name', models.CharField(max_length=254, verbose_name='Full Name')),
                ('designation', models.CharField(blank=True, max_length=10, null=True, verbose_name='Designation')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active?')),
                ('joined_on', models.DateField(blank=True, null=True, verbose_name='Join Date')),
                ('left_on', models.DateField(blank=True, null=True, verbose_name='Leave Date')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Salary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='is_employee', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('doc_type', models.CharField(choices=[('P', 'Pan Card'), ('A', 'AADHAR Card'), ('D', 'Driving License'), ('V', 'Voter ID'), ('PEC', 'Previous Employer Certificate'), ('EDU', 'Education Certificate'), ('OFR', 'Offer Letter'), ('NDA', 'Non Disclosure Agreement')], max_length=5, verbose_name='Document Type')),
                ('doc_value', models.CharField(blank=True, max_length=254, null=True, verbose_name='Document ID')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified?')),
                ('verified_on', models.DateField(blank=True, null=True, verbose_name='Verified On')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.Employee', verbose_name='Employee')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_document', to='employee.Employee')),
            ],
            options={
                'verbose_name': "Employee's Document",
                'verbose_name_plural': "Employee's Documents",
            },
        ),
    ]
