# Generated by Django 2.1.4 on 2019-01-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190105_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
