# Generated by Django 2.1.4 on 2019-01-02 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_auto_20190102_1422'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Amount')),
                ('is_credit', models.BooleanField(default=True, help_text='Is payment towards system?', verbose_name='Is Credit?')),
                ('payment_type', models.CharField(choices=[('C', 'On Counter'), ('O', 'Online')], default='C', max_length=5, verbose_name='Payment Type')),
                ('payment_mode', models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('PTM', 'PayTM'), ('C', 'Cash'), ('IMJ', 'Instamojo'), ('PTMG', 'PayTM Payment Gateway')], default='C', max_length=5, verbose_name='Payment Mode')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
            },
        ),
    ]
