# Generated by Django 2.1.4 on 2019-01-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0005_auto_20190102_1457'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='outlet.OutletManager', verbose_name='Payment Accepted By'),
        ),
    ]
