# Generated by Django 2.0.7 on 2018-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.TextField(verbose_name='Twitter')),
                ('facebook', models.TextField(verbose_name='Facebook')),
                ('instagram', models.TextField(verbose_name='Instagram')),
                ('date', models.DateField(verbose_name='Date')),
                ('verify', models.BooleanField(verbose_name='Verify')),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
    ]
