# Generated by Django 2.0.7 on 2018-07-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Social',
        ),
    ]
