# Generated by Django 2.0.7 on 2018-07-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drfaddons.datatypes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('category', models.CharField(choices=[('V', 'Veg'), ('N', 'Non-Veg'), ('J', 'Jain')], max_length=254, verbose_name='Category')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Item Price')),
                ('image', models.URLField(max_length=254, null=True, verbose_name='Image URL')),
                ('hsn', models.CharField(max_length=20, null=True, verbose_name='HSN (GST)')),
                ('desc', models.TextField(null=True, verbose_name='Description')),
                ('gst', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='GST Percentage')),
                ('gst_inclusive', models.BooleanField(default=True, verbose_name='GST Inclusive?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='LunchPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Item Price')),
                ('category', models.CharField(choices=[('V', 'Veg'), ('N', 'Non-Veg'), ('J', 'Jain')], max_length=254, verbose_name='Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='restaurant.Item')),
            ],
            options={
                'verbose_name': 'Lunch Pack',
                'verbose_name_plural': 'Lunch Packs',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Store Name')),
                ('mobile', models.CharField(max_length=15, null=True, verbose_name='Mobile Number')),
                ('landline', models.CharField(max_length=20, null=True, verbose_name='Landline Number')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('gst_number', models.TextField(null=True, verbose_name='GST Number')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=254, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(to='restaurant.Tag'),
        ),
    ]
