# Generated by Django 2.1.4 on 2018-12-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180916_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
        migrations.AlterField(
            model_name='hasitem',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time'),
        ),
        migrations.AlterField(
            model_name='hasitem',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
        migrations.AlterField(
            model_name='item',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time'),
        ),
        migrations.AlterField(
            model_name='item',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
        migrations.AlterField(
            model_name='lunchpack',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time'),
        ),
        migrations.AlterField(
            model_name='lunchpack',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
        migrations.AlterField(
            model_name='store',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time'),
        ),
        migrations.AlterField(
            model_name='store',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified'),
        ),
    ]
