# Generated by Django 2.0.7 on 2018-07-30 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drfaddons.datatypes


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_auto_20180730_1128'),
        ('restaurant', '0003_auto_20180728_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('profile_pic', models.URLField(blank=True, max_length=254, null=True, verbose_name='Profile Picture')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', drfaddons.datatypes.UnixTimestampField(auto_created=True)),
                ('create_date', drfaddons.datatypes.UnixTimestampField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('P ', 'Pick Up'), ('D', 'Deliver'), ('I', 'Instant')], max_length=20, verbose_name='mode')),
                ('address', models.TextField(verbose_name='Address')),
                ('payment', models.CharField(choices=[('O', 'Online'), ('P', 'Paytm'), ('C', 'Cash')], max_length=254, verbose_name='Payment')),
                ('status', models.CharField(choices=[('1', 'Completed'), ('2', 'Cancel'), ('3', 'in_process')], max_length=254, verbose_name='Status')),
                ('feedback', models.CharField(blank=True, max_length=254, null=True, verbose_name='Feedback')),
                ('wait_time', models.CharField(blank=True, max_length=254, null=True, verbose_name='Wait Time')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.BillingHeader')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='addons',
            field=models.ManyToManyField(to='restaurant.Item'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_addon',
            field=models.BooleanField(default=False, verbose_name='Is Addon'),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HSN (GST)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, max_length=254, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='gst_number',
            field=models.TextField(blank=True, null=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='landline',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Landline Number'),
        ),
        migrations.AlterField(
            model_name='store',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Item'),
        ),
        migrations.AddField(
            model_name='cook',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.Store'),
        ),
    ]
