# Generated by Django 2.0.7 on 2018-08-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20180730_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(blank=True, default='https://officecafe.in/assets/images/logo_whiteback.png', max_length=254, null=True, verbose_name='Image URL'),
        ),
    ]
