# Generated by Django 2.0.7 on 2018-08-10 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('instamojo_raw_response', models.TextField(blank=True, null=True, verbose_name='Payment Raw Response')),
                ('mac', models.CharField(blank=True, max_length=154, null=True, verbose_name='Message Authentication Code')),
                ('status', models.CharField(choices=[('C', 'Credit'), ('F', 'Failed')], default='F', max_length=3, verbose_name='Status')),
                ('fees', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Fees by Instamojo')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Instamojo Payment',
                'verbose_name_plural': 'Instamojo Payment',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='Payment Request ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('purpose', models.CharField(max_length=254, verbose_name='Purpose')),
                ('redirect_url', models.URLField(verbose_name='Redirect URL')),
                ('allow_repeated_payments', models.BooleanField(default=False, verbose_name='Allow Repeated Payment')),
                ('instamojo_raw_response', models.TextField(blank=True, null=True, verbose_name='Payment Request Raw Response')),
                ('longurl', models.URLField(verbose_name='Long URL')),
                ('expires_at', models.CharField(blank=True, max_length=30, null=True, verbose_name='Expires at')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='billing.BillingHeader')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drf_instamojo.PaymentRequest'),
        ),
    ]
