# Generated by Django 2.0.7 on 2018-08-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_instamojo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'verbose_name': 'Payment Request', 'verbose_name_plural': 'Payment Request'},
        ),
    ]
