# Generated by Django 2.1.4 on 2019-01-02 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190102_1422'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date/Time')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Date/Time Modified')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Delivery Amount')),
                ('unit_no', models.CharField(max_length=100, verbose_name='Unit Number / Floor')),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Line 2')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.Area', verbose_name='Area')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.BuildingComplex', verbose_name='Building Complex')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('P', 'PICK UP'), ('D', 'DELIVER')], default='P', max_length=5, verbose_name='Delivery Type'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order.Order', verbose_name='Order'),
        ),
    ]
