# Generated by Django 2.1.7 on 2019-02-16 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190102_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Order Create Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Offline Order Number'),
        ),
    ]
