# Generated by Django 2.1.4 on 2018-12-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181220_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_date'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
